//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatea.AI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatea.AI.Language.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name is {1}..
        /// </summary>
        internal static string EvaluateName_Response {
            get {
                return ResourceManager.GetString("EvaluateName_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in ISpeechGrammarRules.CommitAndSave:  {0}.
        /// </summary>
        internal static string GrammarRules_CommitAndSave_ErrorText_Format {
            get {
                return ResourceManager.GetString("GrammarRules_CommitAndSave_ErrorText_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and then.
        /// </summary>
        internal static string Request_Delimiter {
            get {
                return ResourceManager.GetString("Request_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   and .
        /// </summary>
        internal static string Response_Delimiter {
            get {
                return ResourceManager.GetString("Response_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when invoking the method &apos;SpeechLib.SpVoice.GetVoices().Item({0})&apos;..
        /// </summary>
        internal static string TextToSpeechGetVoicesError {
            get {
                return ResourceManager.GetString("TextToSpeechGetVoicesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY YOU SUBSTITUTION INCORRECTLY??!1.
        /// </summary>
        internal static string TextToSpeechSubstitionsError {
            get {
                return ResourceManager.GetString("TextToSpeechSubstitionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you, you&apos;re.
        /// </summary>
        internal static string Tokens_2nd_Person {
            get {
                return ResourceManager.GetString("Tokens_2nd_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a:default,an:a-e-i-o-u.
        /// </summary>
        internal static string Tokens_Articles {
            get {
                return ResourceManager.GetString("Tokens_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what,what&apos;s.
        /// </summary>
        internal static string Tokens_Evaluate {
            get {
                return ResourceManager.GetString("Tokens_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes,good,great,no,bad,awful.
        /// </summary>
        internal static string Tokens_Feedback {
            get {
                return ResourceManager.GetString("Tokens_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes : Yes, Right, Correct;
        ///Good : Good, Good Job, Nice;
        ///Great : Great, Great Job, Fantastic, Excellent;
        ///MehNo : Um, Eh;
        ///No    : No, Wrong, Sorry;
        ///Bad   : Bad;
        ///Awful : Awful, Terrible, Horrible, You Suck;.
        /// </summary>
        internal static string Tokens_Feedback_Templates {
            get {
                return ResourceManager.GetString("Tokens_Feedback_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it.
        /// </summary>
        internal static string Tokens_It {
            get {
                return ResourceManager.GetString("Tokens_It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        internal static string Tokens_My {
            get {
                return ResourceManager.GetString("Tokens_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color:1,shape:2,symbol:3,letter:4,number:5,name:100.
        /// </summary>
        internal static string Tokens_TemplateType {
            get {
                return ResourceManager.GetString("Tokens_TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colors:1,shapes:2,symbols:3,letters:4,numbers:5,names:100.
        /// </summary>
        internal static string Tokens_TemplateType_Plural {
            get {
                return ResourceManager.GetString("Tokens_TemplateType_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        internal static string Tokens_The {
            get {
                return ResourceManager.GetString("Tokens_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thing,object,widget,blob.
        /// </summary>
        internal static string Tokens_Thing {
            get {
                return ResourceManager.GetString("Tokens_Thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is,are,it&apos;s,its.
        /// </summary>
        internal static string Tokens_ToBe {
            get {
                return ResourceManager.GetString("Tokens_ToBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your.
        /// </summary>
        internal static string Tokens_Your {
            get {
                return ResourceManager.GetString("Tokens_Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #undefined#.
        /// </summary>
        internal static string UNDEFINED {
            get {
                return ResourceManager.GetString("UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s {0} {1}!.
        /// </summary>
        internal static string UserEvaluateInput_NameEntity_Response_Format {
            get {
                return ResourceManager.GetString("UserEvaluateInput_NameEntity_Response_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is {1}..
        /// </summary>
        internal static string UserEvaluateInput_NameTemplate_Response_Format {
            get {
                return ResourceManager.GetString("UserEvaluateInput_NameTemplate_Response_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know the {0}..
        /// </summary>
        internal static string UserEvaluateInput_Response_IDK_Template {
            get {
                return ResourceManager.GetString("UserEvaluateInput_Response_IDK_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what {0} means..
        /// </summary>
        internal static string UserEvaluateInput_Response_IDK_TemplateType {
            get {
                return ResourceManager.GetString("UserEvaluateInput_Response_IDK_TemplateType", resourceCulture);
            }
        }
    }
}
