//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gala.Dolly.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Data\\SerializedData.dat")]
        public string DataAccessManagerConnectionString {
            get {
                return ((string)(this["DataAccessManagerConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MARIA")]
        public string ChatBotName {
            get {
                return ((string)(this["ChatBotName"]));
            }
            set {
                this["ChatBotName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peanut")]
        public string DefaultUserName {
            get {
                return ((string)(this["DefaultUserName"]));
            }
            set {
                this["DefaultUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public short ColorTemplateHybridResultThreshold {
            get {
                return ((short)(this["ColorTemplateHybridResultThreshold"]));
            }
            set {
                this["ColorTemplateHybridResultThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Event")]
        public global::Galatea.Diagnostics.DebuggerLogLevel DebuggerLogLevel {
            get {
                return ((global::Galatea.Diagnostics.DebuggerLogLevel)(this["DebuggerLogLevel"]));
            }
            set {
                this["DebuggerLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message")]
        public global::Galatea.Diagnostics.DebuggerLogLevel DebuggerAlertLevel {
            get {
                return ((global::Galatea.Diagnostics.DebuggerLogLevel)(this["DebuggerAlertLevel"]));
            }
            set {
                this["DebuggerAlertLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <ImagingSettings xmlns:xsi=\"http://www.w3.org/2001/XMLSchem" +
            "a-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                     " +
            "   <Timeout>0</Timeout>\r\n                        <SuppressTimeout>false</Suppres" +
            "sTimeout>\r\n                        <ColorStatsSettings>\r\n                       " +
            "     <StatisticalAnalysisTypes>Mean</StatisticalAnalysisTypes>\r\n                " +
            "        </ColorStatsSettings>\r\n                        <MonochromeBlobFilterSett" +
            "ings>\r\n                            <ContrastCorrectionFactor>0.25</ContrastCorre" +
            "ctionFactor>\r\n                            <AdaptiveSmoothingFactor>0.25</Adaptiv" +
            "eSmoothingFactor>\r\n                            <FrameWidth>10</FrameWidth>\r\n    " +
            "                    </MonochromeBlobFilterSettings>\r\n                        <Bl" +
            "obPointSettings>\r\n                            <LineSegmentThreshold>18</LineSegm" +
            "entThreshold>\r\n                            <LineAngleThreshold>9</LineAngleThres" +
            "hold>\r\n                            <CurveAngleThreshold>27</CurveAngleThreshold>" +
            "\r\n                        </BlobPointSettings>\r\n                        <Templat" +
            "eRecognitionSettings>\r\n                            <ColorBrightnessThreshold>0</" +
            "ColorBrightnessThreshold>\r\n                            <ColorSaturationThreshold" +
            ">0</ColorSaturationThreshold>\r\n                            <ShapeOblongThreshold" +
            ">0</ShapeOblongThreshold>\r\n                            <ShapeOblongRecognitionLe" +
            "vel>0</ShapeOblongRecognitionLevel>\r\n                            <ShapeOblongRec" +
            "ognitionNormalization>false</ShapeOblongRecognitionNormalization>\r\n             " +
            "               <IdentifyShapeCertaintyMinimum>0</IdentifyShapeCertaintyMinimum>\r" +
            "\n                        </TemplateRecognitionSettings>\r\n                    </I" +
            "magingSettings>\r\n                ")]
        public global::Galatea.AI.Imaging.ImagingSettings ImagingSettings {
            get {
                return ((global::Galatea.AI.Imaging.ImagingSettings)(this["ImagingSettings"]));
            }
            set {
                this["ImagingSettings"] = value;
            }
        }
    }
}
