//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galahad.Robotics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineInitializationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineInitializationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galahad.Robotics.Runtime.EngineInitializationResources", typeof(EngineInitializationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Becoming Self-Aware....
        /// </summary>
        internal static string Engine_Initializing_AI {
            get {
                return ResourceManager.GetString("Engine_Initializing_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Initializing Language Modules....
        /// </summary>
        internal static string Engine_Initializing_Language {
            get {
                return ResourceManager.GetString("Engine_Initializing_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Initializing Language Modules [Recognition]....
        /// </summary>
        internal static string Engine_Initializing_Language_Recognition {
            get {
                return ResourceManager.GetString("Engine_Initializing_Language_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Initializing Language Modules [Speech]....
        /// </summary>
        internal static string Engine_Initializing_Language_Speech {
            get {
                return ResourceManager.GetString("Engine_Initializing_Language_Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Initializing Machine Components....
        /// </summary>
        internal static string Engine_Initializing_Machine {
            get {
                return ResourceManager.GetString("Engine_Initializing_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring memory, personality, and characterization....
        /// </summary>
        internal static string Engine_Initializing_Memory {
            get {
                return ResourceManager.GetString("Engine_Initializing_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Robotics Engine : Initializing Visual Processing System....
        /// </summary>
        internal static string Engine_Initializing_Visuals {
            get {
                return ResourceManager.GetString("Engine_Initializing_Visuals", resourceCulture);
            }
        }
    }
}
